<?php

namespace app\models\base\traits;

use app\generation\context\AttributeContext;
use app\generation\context\GenerationContext;
use app\generation\ModelFactory;
use app\models\base\ArmsModel;
use Dom\Attr;
use yii\base\Model;

/**
 * ValidationGenerationTrait
 * 
 * Trait for handling validation rules and generation logic in ArmsModel.
 * Contains methods for applying business rules during model generation.
 */
trait ValidationGenerationTrait
{

    /**
     * Called after attributes are generated by ModelFactory.
     * Applies business rules to ensure model is valid before validation.
     * 
     * @param array $options Generation options
     * @return void
     */
    public function afterGenerate(GenerationContext $context, array $options = []): void
    {
        $this->applyRequireOneOfRules($context, $options);
        $this->applyExistRules($options);
    }

    /**
     * Require at least one attribute from a set to be filled.
     * Validator callback for 'validateRequireOneOf' rule.
     * 
     * @param string $attribute Attribute name
     * @param array $params Parameters with 'attrs' key containing attribute list
     * @return bool
     */
    public function validateRequireOneOf($attribute, $params = [])
    {
        foreach ($params['attrs'] ?? [] as $attr) {
            // If at least one attribute is not empty, validation passes
            if (!static::attrIsEmpty($this, $attr)) {
                return true;
            }
        }
        
        // Add error to all attributes in the set
        foreach ($params['attrs'] ?? [] as $attr) {
            $this->addError($attr, $params['message'] ?? 'Как минимум один аттрибут должен быть заполнен');
        }
        
        return false;
    }

    /**
     * Apply validateRequireOneOf rules during generation.
     * Fills the first suitable attribute if none are filled.
     *
     * @param array $options Generation options
     */
    protected function applyRequireOneOfRules(GenerationContext $context, array $options = []): void
    {
        foreach ($this->rules() as $rule) {
            if (($rule[1] ?? null) !== 'validateRequireOneOf') {
                continue;
            }
            
            $attrs = $rule['params']['attrs'] ?? null;
            if (!is_array($attrs) || empty($attrs)) {
                continue;
            }

            // Check if at least one attribute has a value
            $hasValue = false;
            foreach ($attrs as $attr) {
                if (!static::attrIsEmpty($this, $attr)) {
                    $hasValue = true;
                    break;
                }
            }
            
            if ($hasValue) {
                continue;
            }

            // Выбираем случайный атрибут из набора для заполнения, остальные оставляем пустыми
            $attrSet= $attrs[mt_rand(0, count($attrs) - 1)];

            foreach ($attrs as $attr) {
				//если атрибут не пустой xor нужный
				if ((!$this->attributeIsEmpty($attr)) xor ($attr===$attrSet)) {
					$attrContext=new AttributeContext(
						attribute: $attr,
						attributeData: $this->getAttributeData($attr) ?? [],
						empty: $attr==$attrSet,	//нужный атрибут заполняем значением, остальные пустотой
						model: $this,
						generationContext: $context
					);
					ModelFactory::generateAttribute($attrContext);
				}
			}
        }
    }

    /**
     * Apply exist rules during generation.
     * Creates related models for FK attributes that have 'exist' validator.
     *
     * @param array $options Generation options
     */
    protected function applyExistRules(array $options = []): void
    {
        $linksSchema = method_exists($this, 'getLinksSchema') ? $this->getLinksSchema() : [];

        foreach ($this->rules() as $rule) {
            if (($rule[1] ?? null) !== 'exist') {
                continue;
            }

            $attrs = (array)($rule[0] ?? []);
            $targetClass = $rule['targetClass'] ?? null;
            $targetAttribute = $rule['targetAttribute'] ?? null;
            
            if (!$targetClass) {
                continue;
            }

            foreach ($attrs as $attr) {
                if (!$this->canSetProperty($attr)) {
                    continue;
                }
                
                if (!static::attrIsEmpty($this, $attr)) {
                    continue;
                }
                
                // Skip if linksSchema exists (filled via applyRelations)
                if (is_array($linksSchema) && array_key_exists($attr, $linksSchema)) {
                    continue;
                }

                // Create related model
                $related = \app\generation\ModelFactory::create(
                    $targetClass,
                    [
                        'seed' => ($options['seed'] ?? 0) + crc32($attr),
                        'empty' => $options['empty'] ?? false,
                        'save' => true,
                    ]
                );

                if (!$related) {
                    continue;
                }

                $targetAttr = 'id';
                if (is_array($targetAttribute)) {
                    $targetAttr = $targetAttribute[$attr] ?? 'id';
                } elseif (is_string($targetAttribute)) {
                    $targetAttr = $targetAttribute;
                }

                $value = $related->getPrimaryKey();
                if ($targetAttr !== 'id' && $related->canGetProperty($targetAttr)) {
                    $value = $related->$targetAttr;
                }

                $this->$attr = $value;
            }
        }
    }

		
	/**
	 * Проверяет, что аттрибут или integer или их массив
	 * @param $attribute
	 */
	public function validateIntegerOrArrayOfInteger($attribute)
	{
		if (!is_int($this->$attribute) &&
			!(is_array($this->$attribute) &&
				count(array_filter($this->$attribute, 'is_int')) == count($this->$attribute))) {
			$this->addError($attribute, 'ID должен быть целым числом или массивом целых чисел');
		}
	}
}
